"""Adiciona data previsão em uma conta

Revision ID: 69134531e007
Revises: 04ba39af8bda
Create Date: 2022-11-29 15:58:21.457902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69134531e007'
down_revision = '04ba39af8bda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas_a_pagar_e_receber', sa.Column('data_previsao', sa.DateTime(), nullable=True))
    op.execute("update contas_a_pagar_e_receber set data_previsao = now()")
    op.alter_column('contas_a_pagar_e_receber', 'data_previsao', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contas_a_pagar_e_receber', 'data_previsao')
    # ### end Alembic commands ###
