"""Cria relacionamento entre fornecedor e conta

Revision ID: 901764574d13
Revises: 9ce2d7a2098c
Create Date: 2022-11-11 16:16:54.152875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901764574d13'
down_revision = '9ce2d7a2098c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas_a_pagar_e_receber', sa.Column('fornecedor_cliente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contas_a_pagar_e_receber', 'fornecedor_cliente', ['fornecedor_cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contas_a_pagar_e_receber', type_='foreignkey')
    op.drop_column('contas_a_pagar_e_receber', 'fornecedor_cliente_id')
    # ### end Alembic commands ###
