"""Altera os tipos datetime para date

Revision ID: d7293884ef70
Revises: 69134531e007
Create Date: 2022-11-29 16:05:30.104136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7293884ef70'
down_revision = '69134531e007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('alter table contas_a_pagar_e_receber alter column data_baixa type date')
    op.execute('alter table contas_a_pagar_e_receber alter column data_previsao type date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.execute('alter table contas_a_pagar_e_receber alter column data_baixa type timestamp')
    op.execute('alter table contas_a_pagar_e_receber alter column data_previsao type timestamp')
    # ### end Alembic commands ###
